id: editor
permissions:
  - 'create varbase_blog content'
  - 'delete any varbase_blog content'
  - 'edit any varbase_blog content'
  - 'view varbase_blog revisions'
  - 'view post access counter'
  - 'create terms in blog_categories'
  - 'create terms in tags'
  - 'delete terms in blog_categories'
  - 'delete terms in tags'
  - 'edit terms in blog_categories'
  - 'edit terms in tags'
  - 'reorder terms in blog_categories'
  - 'reorder terms in tags'
  - 'view terms in blog_categories'
  - 'view terms in tags'
